<?xml version="1.0" encoding="UTF-8"?>
<testsuite hostname="QUADUKLT4003" name="script.DataProviderExample" tests="3" failures="1" timestamp="2 May 2011 00:50:18 GMT" time="29.297" errors="0">
  <testcase name="testDataProviderExample on instance null(script.DataProviderExample)" time="8.156" classname="script.DataProviderExample"/>
  <testcase name="testDataProviderExample on instance null(script.DataProviderExample)" time="6.125" classname="script.DataProviderExample"/>
  <testcase name="testDataProviderExample on instance null(script.DataProviderExample)" time="3.36" classname="script.DataProviderExample">
    <failure type="com.thoughtworks.selenium.SeleniumException" message="ERROR: Element xpath=/descendant::a[text()=&amp;apos;The Cows&amp;apos;] not found">
      <![CDATA[com.thoughtworks.selenium.SeleniumException: ERROR: Element xpath=/descendant::a[text()='The Cows'] not found
	at com.thoughtworks.selenium.HttpCommandProcessor.throwAssertionFailureExceptionOrError(HttpCommandProcessor.java:97)
	at com.thoughtworks.selenium.HttpCommandProcessor.doCommand(HttpCommandProcessor.java:91)
	at com.thoughtworks.selenium.DefaultSelenium.click(DefaultSelenium.java:167)
	at script.DataProviderExample.testDataProviderExample(DataProviderExample.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodHelper.invokeMethod(MethodHelper.java:641)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:677)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:850)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1154)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:137)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:121)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1108)
	at org.testng.TestRunner.privateRun(TestRunner.java:737)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:315)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:310)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:272)
	at org.testng.SuiteRunner.run(SuiteRunner.java:221)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1027)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:964)
	at org.testng.TestNG.run(TestNG.java:896)
	at org.testng.TestNG.privateMain(TestNG.java:1193)
	at org.testng.TestNG.main(TestNG.java:1153)
]]>
    </failure>
  </testcase>
</testsuite>
